// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8WST4kzdaQ_hkFGdUQC-orEyyjBdlSs',
    appId: '1:492063792354:web:a047ad96f3662da5f652bb',
    messagingSenderId: '492063792354',
    projectId: 'advanced-store-9dff4',
    authDomain: 'advanced-store-9dff4.firebaseapp.com',
    storageBucket: 'advanced-store-9dff4.firebasestorage.app',
    measurementId: 'G-3WVHRRYCJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-0enx-YdWhM3E8pMfYTU8TuqlNnSvqJk',
    appId: '1:492063792354:android:37155e0cc79df120f652bb',
    messagingSenderId: '492063792354',
    projectId: 'advanced-store-9dff4',
    storageBucket: 'advanced-store-9dff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdM6LpnTFzYl20Wk0v8iEcD_6gvmowCn4',
    appId: '1:492063792354:ios:5bd6be036c7d5ba3f652bb',
    messagingSenderId: '492063792354',
    projectId: 'advanced-store-9dff4',
    storageBucket: 'advanced-store-9dff4.firebasestorage.app',
    iosBundleId: 'com.example.advancedEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdM6LpnTFzYl20Wk0v8iEcD_6gvmowCn4',
    appId: '1:492063792354:ios:5bd6be036c7d5ba3f652bb',
    messagingSenderId: '492063792354',
    projectId: 'advanced-store-9dff4',
    storageBucket: 'advanced-store-9dff4.firebasestorage.app',
    iosBundleId: 'com.example.advancedEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr8WST4kzdaQ_hkFGdUQC-orEyyjBdlSs',
    appId: '1:492063792354:web:44a78c84a261b069f652bb',
    messagingSenderId: '492063792354',
    projectId: 'advanced-store-9dff4',
    authDomain: 'advanced-store-9dff4.firebaseapp.com',
    storageBucket: 'advanced-store-9dff4.firebasestorage.app',
    measurementId: 'G-PQ73N95MXS',
  );
}
